### ISSUE TITLE
DAG CUDA Error

### ISSUE THREAD

**Issue by jeroz1** [RavenCommunity/kawpowminer#3]
Users report a CUDA error on:

- GTX970
- GTX1660Ti
- GTX2060
- GTX2080
- GTX2080Ti

Output: 
```
cu 01:04:30 cuda-0    Generating DAG + Light : 1.26 GB
cu 01:04:30 cuda-0    Unexpected error CUDA error in func set_constants at line 180 calling cudaMemcpyToSymbol(d_dag, &_dag, sizeof(hash64_t*)) failed with error invalid device symbol on CUDA device 08:00.0
cu 01:04:30 cuda-0    Mining suspended ...
```

**Comment by jeroz1** [comment]
Fixed in #7

**Comment by deni64k** [comment]
I still see this error if I build kawpowminer myself.
GTX2080Ti and CUDA 10.2
```
kawpowminer 1.2.2
Build: windows/release/msvc

 i 01:01:52 main      Configured pool us.rvn.minermore.com:5201
 i 01:01:52 <unknown> Selected pool us.rvn.minermore.com:5201
 i 01:01:53 <unknown> Stratum mode : Stratum
 i 01:01:53 <unknown> Established connection to us.rvn.minermore.com [155.138.241.166:5201]
 i 01:01:53 <unknown> Spinning up miners...
cu 01:01:53 cuda-0    Using Pci Id : 65:00.0 GeForce RTX 2080 Ti (Compute 7.5) Memory : 11.00 GB
 i 01:01:53 <unknown> Extranonce set to fd9266
 i 01:01:53 <unknown> New target set to: 000003e418000000000000000000000000000000000000000000000000000000
 i 01:01:53 <unknown> Epoch : 163 Difficulty : 4.31 Mh
 i 01:01:53 <unknown> Job: e6655fc6... block 1226630 us.rvn.minermore.com [155.138.241.166:5201]
 i 01:01:54 <unknown> Authorized worker deni64k.nv2080
cu 01:01:54 cuda-0    Generating DAG + Light : 2.31 GB
cu 01:01:54 cuda-0    Unexpected error CUDA error in func set_constants at line 180 calling cudaMemcpyToSymbol(d_dag, &_dag, sizeof(hash64_t*)) failed with error invalid device symbol on CUDA device 65:00.0
cu 01:01:54 cuda-0    Mining suspended ...
 m 01:01:57 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 01:02:01 main      Got interrupt ...
 i 01:02:01 main      Disconnected from us.rvn.minermore.com [155.138.241.166:5201]
 i 01:02:01 main      Shutting down miners...
 i 01:02:01 main      Terminated!
```

**Comment by morzsa11** [comment]
I have the same issue:
`kawpowminer 1.2.3+commit.d46045ef
Build: windows/release/msvc

Unrecognized platform Intel(R) OpenCL
 i 22:34:11 <unknown> Selected pool localhost:0
 i 22:34:11 <unknown> Established connection to localhost:0
 i 22:34:11 <unknown> Spinning up miners...
cu 22:34:11 cuda-0    Using Pci Id : 01:00.0 GeForce RTX 3080 (Compute 8.6) Memory : 10.00 GB
 i 22:34:11 sim       Epoch : 0 Difficulty : 4.29 Gh
 i 22:34:11 sim       Job: 5d55e005... block 1 localhost:0
 i 22:34:12 sim       Using block 1, difficulty 1
cu 22:34:12 cuda-0    Generating DAG + Light : 1.02 GB
cu 22:34:12 cuda-0    Unexpected error CUDA error in func set_constants at line 180 calling cudaMemcpyToSymbol(d_dag, &_dag, sizeof(hash64_t*)) failed with error invalid device symbol on CUDA device 01:00.0
cu 22:34:12 cuda-0    Mining suspended ...
 m 22:34:16 <unknown> 0:00 A0 0.00 h - cu0 0.00
 i 22:34:18 main      Got interrupt ...
 i 22:34:18 main      Simulation results : Max 0.000000 h Mean 0.000000 h
 i 22:34:18 main      Disconnected from localhost:0
 i 22:34:18 main      Shutting down miners...
 i 22:34:19 main      Terminated!`
